---
- name: nxos acl testing
  hosts: nexus9k1
  gather_facts: false
  vars:
#    acl_name: test

  tasks:
  - name: Parse given config to structured data
    cisco.nxos.nxos_acls:
      running_config: "{{ lookup('file', 'nexus-acl-template') }}"
#      running_config: |
#        ip access-list ACL1v4
#          50 deny tcp any lt 55 192.0.2.64 0.0.0.255 ack fin
#        ipv6 access-list ACL1v6
#          10 permit sctp any any
      state: parsed
    register: acl_parsed
 
#  - name: debut the acl_parsed variable
#    debug:
#      var: acl_parsed

  - name: Do reconciliation of parsed ACL
    cisco.nxos.nxos_acls:
      config: "{{ acl_parsed.parsed }}"
      state: replaced
    register: acl_ran

  - name: Debug when changed
    when: acl_ran.changed == true
    debug:
      var: acl_ran.commands
